### ISSUE TITLE
navigational map

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/Newberry-French-paleography#11]
API call: https://frp.carto.com:443/api/v2/sql?q=select * from public.frp_2016_01_25_arcmap10_3

Navigational Map: https://frp.carto.com/tables/frp_2016_01_25_arcmap10_3/public

**Comment by thehabes** [comment]
That endpoint does not return GeoJSON, or any other kind of usable data without serious scripting.

**Comment by thehabes** [comment]
It returns 
```JSON
{
 "fields":[,,,],
 "rows":[...]
}
```
fields are all useless.

rows look like
```JSON
{
cartodb_id: 5
city: "Asnelles"
doclink1: "https://paleography-beta.library.utoronto.ca/islandora/search/catch_all_fields_mt:%28Asnelles%29"
doclink2: "http://tinyurl.com/jcxpcwh"
identifier: "FP_338"
imageright: null
region: "France--Northern France"
the_geom: "0101000020E6100000EBB6FAA01DA6E2BFEA526D814EAB4840"
the_geom_webmercator: "0101000020110F0000F5D5E5E450ADEFC000C9E16B0C285841"
title: "Land sale by Pierre le Canu"
x_long: -0.582778
y_lat: 49.338333
}
```

I can loop each row and generate a GeoJSON representation of it and feed that into Leaflet, but that's nonsense.  Anyway to get GeoJSON from an endpoint?

**Comment by thehabes** [comment]
![image](https://user-images.githubusercontent.com/3287006/101210519-3845c900-363b-11eb-932a-b07f4bad350f.png)

ain't no thing
