### ISSUE TITLE
Indicate User is Logged In

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/Newberry-French-paleography#34]
The logout button is always just Logout, and there is nothing anywhere telling me that I am logged in or who I am logged in as.

Do we want to do that on the static pages?

**Comment by cubap** [comment]
tricky. The planned feature of showing their info and detecting logged in is cancelled. We can sort of do it with iframes and some other hacks, but maybe we just remove this?

**Comment by thehabes** [comment]
Yeah if it is cancelled then we should just remove the "logout" option.
